### ISSUE TITLE
Fable 2 build: Cannot find Fable.Core JS files

### ISSUE THREAD

**Issue by et1975** [elmish/sample-react-counter#3]
I've reset the master branch on v1.x and upgraded it to use Fable2 dependencies.
The build fails and it starts with:

>[WARNING] Cannot find Fable.Core JS files location for project app.fsproj, using `fable-core`. Add a reference to Fable.Core package or set the fableCore option in the JS client.

and ends with errors like this:

>ERROR in /Users/eugene.tolmachev/.nuget/packages/fable.elmish.react/2.0.0-beta-4/fable/common.fs
>Module Error (from ./node_modules/fable-loader/index.js):
>/Users/eugene.tolmachev/.nuget/packages/fable.elmish.react/2.0.0-beta-4/fable/common.fs(829,18): (829,31) error FABLE: Cannot find replacement for Fable.Core.JsInterop::jsConstructor
 @ /Users/eugene.tolmachev/.nuget/packages/fable.elmish.react/2.0.0-beta-4/fable/react.fs 3:0-37 16:15-21 27:13-19 37:14-20
 @ ./src/app.fs
 @ ./src/app.fsproj
 @ multi babel-polyfill ./src/app.fsproj

@alfonsogarciacaro @MangelMaxime any idea what's wrong?

**Comment by MangelMaxime** [comment]
@et1975 Did you update fable-loader to `2.0.0-alpha-003` ?

You also, need to adapt the webpack config. We made a commented template available [here](https://github.com/fable-compiler/webpack-config-template)

**Comment by et1975** [comment]
I've pushed the updated master, maybe you could take a look?

**Comment by et1975** [comment]
Btw, I tried with your webpack config - same problem.

**Comment by alfonsogarciacaro** [comment]
What's the branch updated to Fable 2? I don't see the updated dependencies in packet.lock in master. Please make sure you've updated both dotnet-fable and Fable.Core (and Fable.React prerelease too).

And also fable-loader in package.json as Maxime remarks.

**Comment by et1975** [comment]
Oops, so sorry, I was positive I've pushed the update to the master! Pushed now.
From what I can see everything is updated, wepback conf is not like in your template, but I think it's equivalent (and I've tried yours as well).

**Comment by alfonsogarciacaro** [comment]
Thanks @et1975 :+1: Dependencies are updated but it seems you're [still using Fable 1](https://github.com/elmish/sample-react-counter/blob/d17a259eb15f8ac0489f6feae24da03b9585fac0/paket.lock#L5). I guess you need to add `prerelease` to `clitool dotnet-fable` in paket.dependencies.

There're two many things to update, sorry! We should try to find a way to easily automate the process.

**Comment by et1975** [comment]
Duh, of course! All good now, thank you!
